# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CompanyInventory-iOS' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CompanyInventory-iOS
  
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'RealmSwift'
  pod 'GoogleMaps'
  pod 'IQKeyboardManagerSwift', '~> 5.0'
  pod 'lottie-ios'

  target 'CompanyInventory-iOSTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RealmSwift'
  end

end
